### ISSUE TITLE
How remove relationship?

### ISSUE THREAD

**Issue by actorius** [samselikoff/ember-cli-mirage#517]
Hello, have shortland example 

``` javascript
*config.js*
this.patch('/web-modules/:id');
*models/web-module.js*
import { Model, belongsTo } from 'ember-cli-mirage';
export default Model.extend({
  dcModule: belongsTo()
});
*models/dc-module.js*
import { Model, belongsTo } from 'ember-cli-mirage';
export default Model.extend({
  webModule: belongsTo()
});
*scenario/default.js*
 for (var i = 0; i < 5; i++) {
        let m = server.create('dc-module');
        server.createList('web-module', 1, { dcModuleId: m.id });
    }
*request*
Successful request: PATCH /web-modules/1
```

in debuger i can see that requested data:

```
{
   "data": {
      "id": "1",
      "attributes": {
         ...
      },
      "relationships": {
         "dc-module": {
            "data": null
         }
      },
      "type": "web-modules"
   }
}
```

but in response i see again relation id:

```
data: 
   attributes: ..
   id: "1"
   relationships: 
     dc-module: 
        data: 
           id: "1"
           type: "dc-modules"
type: "web-modules"
```
